import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';

export default function Home() {
  const [randomArray, setRandomArray] = useState([]);
  const items = ['Lone Wolf', 'Blown Away', 'Earing', 'White Suit', 'Uzi', 'Drugs', 'Crow', 'Tom', 'Mike', 'Joel', 'Ash', 'Laughing', 'Smiling', 'High', 'Experiment', 'Matter', 'Peanut', 'Butter', 'Crowds', 'Penny', 'AshPow', 'Shepshep', 'Michelle', 'Monster', 'Secrets', 'So Sorry', 'Really Nice', 'Swag', 'Loyly', 'Next Time', 'Miranda'];
    
  useEffect(() => {
      const randomizeArray = [...items].sort(() => 0.5 - Math.random());
      setRandomArray(randomizeArray.slice(0, 24));
  }, []);
  
  const handleClick = (event) => {
    event.currentTarget.classList.toggle('active');
    event.currentTarget.style.backgroundColor = 'transparent';

    if (event.currentTarget.classList.contains('active')) {
      event.currentTarget.style.backgroundColor = 'green';
    } 
  }
  
  const gridItems = randomArray.map(item => {
    return <li key={item} onClick={handleClick} className={styles.gridItem}>
              <span>{item}</span>
            </li>
  })


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
        <h1 className={styles.title}>B Movie Bingo</h1>
          <div className={styles.gridContainer}>
            {gridItems}
            <div className={styles.blankSquare} onClick={handleClick}>Blank Square</div>
          </div>
        </div>
      </main>
    </>
  )
}
